package xyz.ohmycs.bjwiber

import javafx.application.Application
import javafx.stage.Stage

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class App : Application() {
    override fun start(primaryStage: Stage?) {
        primaryStage!!.show()
    }

    val greeting: String
        get() = "Hello world."

    companion object {

        @JvmStatic fun main(args: Array<String>) {
            println(App().greeting)
            val foo = Foo()
            Foo.greet()
            println(foo)
            launch(App::class.java)
        }
    }
}
